package com.iplanalyser;

public enum  SortedField {
    AVERAGE, STRIKE_RATE,NO_OF_4S_AND_6S, BEST_RUNS_WITH_BEST_AVG, BEST_FOURS_AND_SIX_WITH_STRIKING_RATE, BEST_AVG_WITH_STRIKE_RATE, ECONOMY_RATE, STRIKE_RATE_WITH_4_AND_5_WICKET, BEST_BOWLING_AVG_WITH_BEST_STRIKE_RATE, MAX_WICKETS_WITH_BEST_BOWLING_AVERAGE, ALL_ROUNDER, BEST_BATTING_BOWLING_AVG;
}
